# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4884c001415d87df0d51861c133945507b3b79dbbb010a2e4262da2869641ab6b98c740e0d6d77b5f20d01bf2772c1bcd61489a9db78166797c51f730396e778

test:
  secret_key_base: 0843dcd048668621a72ba46c5576e891c441ba6a5aa5e708dcc60d84a7916e61cec1f4b6e924a7042b0731ab7f6913fa1b215afe501a0242ae578c039f2a48a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
